version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php-fpm
    networks:
      - mynetwork

  php-fpm:
    build: 
      dockerfile: ./Dockerfile
    networks:
      - mynetwork
    volumes:
      - ./app:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
