version: "3"
services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "90:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./app:/var/www/html
  #     - ./logs/nginx:/var/log/nginx/
  #   networks:
  #     - secondnetwork
  #   depends_on:
  #     - goservice
  goservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "90:8080"
    command: air -c .air.toml
    networks:
      - secondnetwork
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
networks:
  secondnetwork:
    driver: bridge