version: "3.7"
services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "90:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./app:/var/www/html
  #     - ./logs/nginx:/var/log/nginx/
  #   networks:
  #     - secondnetwork
  #   depends_on:
  #     - goservice
  goservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "90:8080"
    command: air -c .air.toml
    networks:
      - my-network
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "movie_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/docker-entrypoint-initdb.d
    networks:
      - my-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
networks:
  my-network:
    external: true